/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe, used by the container health check.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse
         * @description Interpret text as a numeric table and report how it was read.
         *
         *     Performs no physics. Separate from the analysis so that a misread file is
         *     caught before any computation and before any unit is chosen (FR-003).
         */
        post: operations["parse_api_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lambda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lambda Table
         * @description Per-temperature inversion only, without a gap fit (FR-006, FR-007).
         *
         *     Useful when the data are too sparse to fit a gap, or when the user only
         *     wants to look at lambda(T) and kappa(T).
         */
        post: operations["lambda_table_api_lambda_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description The full chain from Jc to the gap.
         *
         *     Uncertainty propagation is not done here: it is slow, and FR-018 requires
         *     the page to stay usable while it runs. See POST /api/uncertainty.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uncertainty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Uncertainty
         * @description Start a Monte Carlo run in the background and return its identifier.
         *
         *     The dataset and settings are validated here, synchronously, so that a
         *     misconfiguration is refused immediately rather than after minutes of
         *     computation.
         */
        post: operations["start_uncertainty_api_uncertainty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Csv
         * @description Render a completed analysis as a spreadsheet-readable table (FR-027).
         *
         *     One row per measured temperature: the inverted quantities, and the fit's
         *     view of that same point.
         */
        post: operations["export_csv_api_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/curve.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Curve Csv
         * @description Render the fitted model curve as a table (FR-027a).
         *
         *     A separate resource from the table above because the two have different row
         *     counts, and a spreadsheet column cannot be half one thing and half another:
         *     that table has one row per measurement, this one has however many points
         *     the curve was sampled at, on a grid chosen without reference to where the
         *     measurements happen to lie.
         *
         *     Exports exactly what was plotted. Resampling it here would give the user a
         *     file that disagrees with the figure they are looking at, which is a defect
         *     that would surface only in someone else's paper.
         */
        post: operations["export_curve_csv_api_export_curve_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            dataset: components["schemas"]["Dataset"];
            settings: components["schemas"]["Settings"];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            lambda_table: components["schemas"]["LambdaResponse"];
            fit: components["schemas"]["FitResultOut"];
            curve: components["schemas"]["SuperfluidCurveOut"];
            diagnostics: components["schemas"]["DiagnosticReportOut"];
            settings: components["schemas"]["Settings"];
            uncertainty?: components["schemas"]["UncertaintyResultOut"] | null;
        };
        /**
         * CoherenceSource
         * @description How the coherence length is established at each temperature.
         * @enum {string}
         */
        CoherenceSource: "FROM_HC2" | "EXPLICIT_XI" | "FIXED_KAPPA";
        /**
         * CorrelationMode
         * @description Whether a stated input uncertainty is one calibration error shared by the
         *     whole dataset or scatter redrawn at every temperature. Research R8.3 shows
         *     the two give materially different uncertainties on Delta(0).
         * @enum {string}
         */
        CorrelationMode: "SYSTEMATIC" | "INDEPENDENT";
        /**
         * CouplingRegime
         * @enum {string}
         */
        CouplingRegime: "BELOW_BCS" | "WEAK_COUPLING_BCS" | "MODERATELY_STRONG" | "STRONG_COUPLING" | "UNDETERMINED";
        /**
         * Dataset
         * @description Measured columns, together with the units they are expressed in.
         */
        Dataset: {
            /** Temperature K */
            temperature_K: number[];
            /** Jc */
            jc: number[];
            /** @default A_PER_CM2 */
            jc_unit: components["schemas"]["JcUnit"];
            /**
             * Hc2 T
             * @description Required when coherence_source is FROM_HC2
             */
            hc2_T?: number[] | null;
            /**
             * Xi
             * @description Required when coherence_source is EXPLICIT_XI
             */
            xi?: number[] | null;
            /** @default NM */
            xi_unit: components["schemas"]["XiUnit"];
        };
        /** DiagnosticReportOut */
        DiagnosticReportOut: {
            /** Chi2 Reduced */
            chi2_reduced: number;
            /** Chi2 Clean */
            chi2_clean?: number | null;
            /** Chi2 Dirty */
            chi2_dirty?: number | null;
            preferred_model?: components["schemas"]["GapModel"] | null;
            /** Delta Aic */
            delta_aic?: number | null;
            /** Preferred Model Weight */
            preferred_model_weight?: number | null;
            /** Coupling Ratio */
            coupling_ratio: number;
            coupling_regime: components["schemas"]["CouplingRegime"];
            /**
             * Bcs Ratio Reference
             * @description Supplied so the frontend never hard-codes a physical constant
             */
            bcs_ratio_reference: number;
            /** T Min Over Tc */
            t_min_over_tc: number;
            /** Kappa Min */
            kappa_min: number;
            /** Kappa Max */
            kappa_max: number;
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
        };
        /**
         * ErrorPayload
         * @description The only failure shape the API returns (constitution IV).
         */
        ErrorPayload: {
            /**
             * Code
             * @description Stable identifier from the data-model.md catalogue
             */
            code: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** FitResultOut */
        FitResultOut: {
            gap_model: components["schemas"]["GapModel"];
            fit_route: components["schemas"]["FitRoute"];
            /**
             * Converged
             * @description When false the frontend must not present this as a result
             */
            converged: boolean;
            lambda0_m: components["schemas"]["FittedParameter"];
            lambda0_nm: components["schemas"]["FittedParameter"];
            delta0_J: components["schemas"]["FittedParameter"];
            delta0_meV: components["schemas"]["FittedParameter"];
            tc_K: components["schemas"]["FittedParameter"];
            coupling_ratio: components["schemas"]["FittedParameter"];
            /** Chi2 Reduced */
            chi2_reduced: number;
            /** Residuals */
            residuals: number[];
            /**
             * Rho S Measured
             * @description lambda0^2 / lambda^2 at each measured point, for plotting
             */
            rho_s_measured: number[];
            /**
             * Jc Model A Per M2
             * @description equation (1) at the fitted parameters, at each measured temperature; on the measurements rather than on a dense grid because xi is known only there (FR-026a)
             */
            jc_model_A_per_m2: number[];
            /** N Points */
            n_points: number;
            /** N Free Parameters */
            n_free_parameters: number;
            /** N Function Evaluations */
            n_function_evaluations: number;
        };
        /**
         * FitRoute
         * @description TWO_STEP fits lambda(T) obtained by inverting equation (1) point by
         *     point. DIRECT fits the measured Jc(T) in one pass. Research R6.
         * @enum {string}
         */
        FitRoute: "TWO_STEP" | "DIRECT";
        /** FittedParameter */
        FittedParameter: {
            /** Value */
            value: number;
            /**
             * Stderr
             * @description null when the covariance matrix is singular
             */
            stderr?: number | null;
            /**
             * Fixed
             * @default false
             */
            fixed: boolean;
        };
        /**
         * GapModel
         * @enum {string}
         */
        GapModel: "CLEAN" | "DIRTY";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * JcUnit
         * @enum {string}
         */
        JcUnit: "A_PER_CM2" | "A_PER_M2";
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            state: components["schemas"]["JobState"];
            /** Progress */
            progress: number;
            result?: components["schemas"]["UncertaintyResultOut"] | null;
            error?: components["schemas"]["ErrorPayload"] | null;
        };
        /** LambdaRequest */
        LambdaRequest: {
            dataset: components["schemas"]["Dataset"];
            settings: components["schemas"]["Settings"];
        };
        /**
         * LambdaResponse
         * @description SI is always present; the nm columns are additions for display.
         */
        LambdaResponse: {
            /** Temperature K */
            temperature_K: number[];
            /** Jc A Per M2 */
            jc_A_per_m2: number[];
            /** Xi M */
            xi_m: number[];
            /** Xi Nm */
            xi_nm: number[];
            /** Lambda M */
            lambda_m: number[];
            /** Lambda Nm */
            lambda_nm: number[];
            /** Kappa */
            kappa: number[];
            /** Warnings */
            warnings?: components["schemas"]["WarningOut"][];
        };
        /** ParameterDistribution */
        ParameterDistribution: {
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
        };
        /** ParseRequest */
        ParseRequest: {
            /**
             * Text
             * @description File contents or pasted text
             */
            text: string;
            /**
             * Comment Prefix
             * @default #
             */
            comment_prefix: string;
        };
        /** ParseResponse */
        ParseResponse: {
            /** N Rows */
            n_rows: number;
            /** N Columns */
            n_columns: number;
            /** Header Detected */
            header_detected: boolean;
            /** Column Names */
            column_names: string[];
            /**
             * Preview
             * @description First rows, for the user to confirm
             */
            preview: number[][];
            /**
             * Values
             * @description The full table, in the file's own units
             */
            values: number[][];
        };
        /** Settings */
        Settings: {
            coherence_source: components["schemas"]["CoherenceSource"];
            /**
             * Kappa Fixed
             * @description Required when coherence_source is FIXED_KAPPA
             */
            kappa_fixed?: number | null;
            /** @default CLEAN */
            gap_model: components["schemas"]["GapModel"];
            /** @default TWO_STEP */
            fit_route: components["schemas"]["FitRoute"];
            /**
             * Tc Fixed K
             * @description When present, Tc is held rather than fitted
             */
            tc_fixed_K?: number | null;
            /**
             * Film Thickness Nm
             * @description Diagnostics only; never enters the physics
             */
            film_thickness_nm?: number | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "INFO" | "WARNING" | "ERROR";
        /** SuperfluidCurveOut */
        SuperfluidCurveOut: {
            /** Temperature K */
            temperature_K: number[];
            /** Rho S */
            rho_s: number[];
            /** Lambda Nm */
            lambda_nm: number[];
            /**
             * Jc A Per M2
             * @description Equation (1) along the curve. Null where the coherence length is not available without an added assumption (FR-026a)
             */
            jc_A_per_m2: (number | null)[];
        };
        /** UncertaintyRequest */
        UncertaintyRequest: {
            dataset: components["schemas"]["Dataset"];
            settings: components["schemas"]["Settings"];
            uncertainty: components["schemas"]["UncertaintySettingsIn"];
        };
        /** UncertaintyResultOut */
        UncertaintyResultOut: {
            lambda0_nm: components["schemas"]["ParameterDistribution"];
            delta0_meV: components["schemas"]["ParameterDistribution"];
            tc_K: components["schemas"]["ParameterDistribution"];
            coupling_ratio: components["schemas"]["ParameterDistribution"];
            /** N Valid */
            n_valid: number;
            /** N Requested */
            n_requested: number;
            /** @description Echoed verbatim including the seed, so the result is reproducible */
            settings: components["schemas"]["UncertaintySettingsIn"];
            /** Warnings */
            warnings?: components["schemas"]["WarningOut"][];
        };
        /**
         * UncertaintySettingsIn
         * @description Percentages here, fractions in the core.
         *
         *     The percentage is what an experimentalist writes down; the fraction is what
         *     the arithmetic wants. The conversion belongs at this boundary and nowhere
         *     else.
         */
        UncertaintySettingsIn: {
            /**
             * Jc Error Percent
             * @default 0
             */
            jc_error_percent: number;
            /**
             * Hc2 Error Percent
             * @default 0
             */
            hc2_error_percent: number;
            /**
             * Xi Error Percent
             * @default 0
             */
            xi_error_percent: number;
            /**
             * Kappa Error Percent
             * @default 0
             */
            kappa_error_percent: number;
            /** @default SYSTEMATIC */
            correlation_mode: components["schemas"]["CorrelationMode"];
            /**
             * N Samples
             * @default 5000
             */
            n_samples: number;
            /**
             * Confidence Percent
             * @default 68.27
             */
            confidence_percent: number;
            /**
             * Seed
             * @default 12345
             */
            seed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarningOut */
        WarningOut: {
            /** Code */
            code: string;
            severity: components["schemas"]["Severity"];
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * XiUnit
         * @enum {string}
         */
        XiUnit: "M" | "NM" | "UM";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    parse_api_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lambda_table_api_lambda_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LambdaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LambdaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_uncertainty_api_uncertainty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UncertaintyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_export_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_curve_csv_api_export_curve_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
