"""Read the built-in example datasets from disk.

Separate from `core/` because the core is forbidden to touch the filesystem
(constitution I), and separate from the routes because reading files is not a
transport concern either.

The files themselves are generated by `examples/generate.py` from stated
parameters, so that what an example claims in its header is something it
actually delivers.
"""

from __future__ import annotations

import json
import pathlib
from functools import lru_cache

from .core.errors import CoreError

EXAMPLES_DIR = pathlib.Path(__file__).resolve().parents[1] / "examples"
MANIFEST = EXAMPLES_DIR / "manifest.json"


class ExampleNotFound(CoreError):
    """params: name"""
    code = "EXAMPLE_NOT_FOUND"


@lru_cache(maxsize=1)
def manifest() -> list[dict]:
    """The example catalogue. Cached: it does not change while running."""
    if not MANIFEST.is_file():
        return []
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def summaries() -> list[dict]:
    return [
        {
            "name": entry["name"],
            "title": entry["title"],
            "coherence_source": entry["coherence_source"],
            "n_points": entry["n_points"],
            "expects_model_preference": entry["expects_model_preference"],
        }
        for entry in manifest()
    ]


def load(name: str) -> dict:
    """One example, with its file contents and the settings it was built for."""
    for entry in manifest():
        if entry["name"] == name:
            path = EXAMPLES_DIR / entry["file"]
            if not path.is_file():
                raise ExampleNotFound(name=name)
            return {
                "name": entry["name"],
                "title": entry["title"],
                "coherence_source": entry["coherence_source"],
                "n_points": entry["n_points"],
                "expects_model_preference": entry["expects_model_preference"],
                "text": path.read_text(encoding="utf-8"),
                "suggested_settings": entry["suggested_settings"],
            }
    raise ExampleNotFound(name=name)
